name: AWS OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::870318142654:role/GitHubActionsTerraformPlan
          aws-region: eu-north-1
          allowed-account-ids: 870318142654

      - name: Check AWS identity
        run: aws sts get-caller-identity