name: Terraform Apply

on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read
jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::870318142654:role/GitHubActionsTerraformPlan
          aws-region: eu-north-1
          allowed-account-ids: 870318142654

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v7
        with:
          name: terraform-plan
          path: tfplan
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::870318142654:role/GitHubActionsTerraformApply
          aws-region: eu-north-1
          allowed-account-ids: 870318142654

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init -input=false

      - name: Download Terraform Plan
        uses: actions/download-artifact@v5
        with:
          name: terraform-plan

      - name: Terraform Apply
        run: terraform apply -input=false -lock-timeout=2m tfplan
